### ISSUE TITLE
UniqueAscs.pm: Gender?

### ISSUE THREAD

**Issue by actual-nh** [tnnt-devteam/tnnt-backend#1]
https://github.com/tnnt-devteam/tnnt-backend/blob/fa06e43f45c662caf019d00e7b19ce2c0979c3a7/TNNT/Tracker/UniqueAscs.pm#L78

Hi. Why is 'gender0' included in this? (It is not listed as included in the "most unique ascensions" trophy.)

**Comment by actual-nh** [comment]
From counting the number of unique combos (which do include gender) in the example config file and comparing it to the trophy tooltext, I've concluded that the problem (assuming people want gender to matter) is actually in the "Nethack Master" and "Most Unique Ascensions" trophy tooltips, which say that only role/race/align0 combinations are counted (but have the 73 - which is with gender0 - from the config file).

**Comment by k21971** [comment]
Thanks for bringing this to our attention. The tooltip for each trophy neglected to mention gender0 as part of the criteria. Fixed via commit 6496fd5.
